env:
  browser: true
  es2021: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules:
  no-unused-vars:
    - warn
    - argsIgnorePattern: "^_"
      args: none
globals:
  "$SCRIPT_ROOT": readonly
  d3: readonly
  dc: readonly
