env:
  browser: true
  es2021: true
extends:
  # TODO when everything is on ts, switch the rulesets
  - "eslint:recommended"
  # - "plugin:@typescript-eslint/recommended"
# use `--ext=.js,.ts` to also test `.ts` files
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - "@typescript-eslint"
rules:
  no-unused-vars:
    - warn
    - argsIgnorePattern: "^_"
      args: none
globals:
  "$SCRIPT_ROOT": readonly
  d3: readonly
  dc: readonly
