---
version: '2.3'

services:
  base:
    build:
      context: docker/base
      dockerfile: ../base.Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    image: agdsn/pycroft-base:${TAG:-latest}
    entrypoint: ["/bin/true"]
    command: []
  dev-base:
    build:
      context: docker/dev
      dockerfile: ../dev.Dockerfile
    image: agdsn/pycroft-dev:${TAG:-latest}
    environment:
      - PYCROFT_DB_URI=postgresql://postgres:password@db:5432/pycroft
      - PYCROFT_API_KEY=secret
      - PYCROFT_LDAP_HOST=ldap
      - PYCROFT_LDAP_PORT=389
      - PYCROFT_LDAP_BIND_DN=cn=admin,dc=agdsn,dc=de
      - PYCROFT_LDAP_BIND_PW=password
      - PYCROFT_LDAP_BASE_DN=ou=pycroft,dc=agdsn,dc=de
      - HADES_CELERY_APP_NAME=dummy_tasks
      - HADES_BROKER_URI=amqp://celery:celery@mq:5672/
      - HADES_RESULT_BACKEND_URI=rpc://celery:celery@mq:5672/
  dev:
    extends: dev-base
    volumes:
      - "home:/opt/pycroft"
      - ".:/opt/pycroft/app"
  db:
    build:
      context: ./docker/db
      dockerfile: ../db.Dockerfile
    environment:
      - TZ=Etc/UTC
      - POSTGRES_DB=pycroft
      - POSTGRES_PASSWORD=password
      - POSTGRES_INITDB_ARGS=--locale=C --encoding=UTF-8
  ldap:
    image: dinkel/openldap
    environment:
      - SLAPD_PASSWORD=password
      - SLAPD_DOMAIN=agdsn.de
      - SLAPD_ADDITIONAL_SCHEMAS=ppolicy
      - SLAPD_ADDITIONAL_MODULES=ppolicy
  mq:
    image: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=celery
      - RABBITMQ_DEFAULT_PASS=celery
  dummy-worker:
    extends:
      service: dev
    command: ["python", "helpers/dummy_celery_worker.py", "worker"]
    environment:
      - TEST_HADES_BROKER_URI=amqp://celery:celery@mq:5672/
      - TEST_HADES_RESULT_BACKEND_URI=rpc://celery:celery@mq:5672/

