---
services:
  base:
    build:
      context: docker/base
      dockerfile: ../base.Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    image: agdsn/pycroft-base:${TAG:-latest}
    entrypoint: ["/bin/true"]
    command: []
  dev-base:
    build:
      context: docker/dev
      dockerfile: ../dev.Dockerfile
      x-bake:
        contexts:
          pycroft-base: target:base
    image: agdsn/pycroft-dev:${TAG:-latest}
    environment:
      PYTHONDEVMODE: 1
      PYCROFT_DB_URI: postgresql://postgres:password@db:5432/pycroft?options=-csearch_path%3Dpycroft,public
      PYCROFT_API_KEY: secret
      PYCROFT_LDAP_HOST: ldap
      PYCROFT_LDAP_PORT: 389
      PYCROFT_LDAP_BIND_DN: cn=admin,dc=agdsn,dc=de
      PYCROFT_LDAP_BIND_PW: password
      PYCROFT_LDAP_BASE_DN: ou=pycroft,dc=agdsn,dc=de
      PYCROFT_CELERY_BROKER_URI: amqp://celery:celery@mq:5672/
      PYCROFT_CELERY_RESULT_BACKEND_URI: rpc://celery:celery@mq:5672/
      PYCROFT_MAIL_ENVELOPE_FROM: pycroft@agdsn.de
      PYCROFT_MAIL_FROM: AG DSN <support@agdsn.de>
      PYCROFT_SMTP_HOST: mail
      PYCROFT_SMTP_PORT: 2500
      PYCROFT_SMTP_USER: ''
      PYCROFT_SMTP_SSL: ''
      PYCROFT_SMTP_PASSWORD: ''
      # PYCROFT_TEMPLATE_PATH: 'pycroft/templates'
      HADES_CELERY_APP_NAME: dummy_tasks
      HADES_BROKER_URI: amqp://celery:celery@mq:5672/
      HADES_RESULT_BACKEND_URI: rpc://celery:celery@mq:5672/
      SWDD_HASH_KEY: key
      MAIL_CONFIRM_URL: "http://localhost/sipa/register/confirm/{}"
      PASSWORD_RESET_URL: "http://localhost/sipa/reset-password/{}"
      FLASK_ENV: development
  dev:
    extends: dev-base
    volumes:
      - "home:/opt/pycroft"
      - ".:/opt/pycroft/app"
  db:
    build:
      context: ./docker/db
      dockerfile: ../db.Dockerfile
    environment:
      - TZ=Etc/UTC
      - POSTGRES_DB=pycroft
      - POSTGRES_PASSWORD=password
      - POSTGRES_INITDB_ARGS=--locale=C --encoding=UTF-8
    healthcheck:
      test: pg_isready -U postgres
      interval: 2s
      timeout: 2m
  ldap:
    image: dinkel/openldap
    environment:
      - SLAPD_PASSWORD=password
      - SLAPD_DOMAIN=agdsn.de
      - SLAPD_ADDITIONAL_SCHEMAS=ppolicy,custom/group-of-members
      - SLAPD_ADDITIONAL_MODULES=ppolicy
    volumes:
      - ./docker/ldap/schema:/etc/ldap/schema/custom
    healthcheck:
      test: "slapdn cn=config"
      interval: 2s
  mq:
    image: rabbitmq:3.8-management
    environment:
      - RABBITMQ_DEFAULT_USER=celery
      - RABBITMQ_DEFAULT_PASS=celery
    healthcheck:
      test: rabbitmq-diagnostics check_running
      start_period: 30s
      interval: 5s
      timeout: 2m
  mail:
    build:
      context: ./docker/
      dockerfile: mail.Dockerfile
