---
services:
  base:
    extends:
      file: docker-compose.base.yml
      service: base
  dev-app:
    extends:
      file: docker-compose.base.yml
      service: dev
    security_opt:
      - "seccomp:unconfined"
    depends_on:
      - dev-db
      - dev-ldap
      - dev-mq
      - dev-webpack
    networks:
      dev:
        aliases:
          - app
    ports:
      - "5000:5000"
    command: ["http", "--debug"]
  dev-webpack:
    extends:
      file: docker-compose.base.yml
      service: dev
    command: ["webpack", "--watch"]
  dev-db:
    extends:
      file: docker-compose.base.yml
      service: db
    networks:
      dev:
        aliases:
          - db
    volumes:
      - "db:/var/lib/postgresql"
    ports:
    - "55432:5432"
  dev-ldap:
    extends:
      file: docker-compose.base.yml
      service: ldap
    networks:
      dev:
        aliases:
          - ldap
    volumes:
      - "ldap:/var/lib/ldap"
  dev-mq:
    extends:
      file: docker-compose.base.yml
      service: mq
    networks:
      dev:
        aliases:
          - mq
    volumes:
      - "mq:/var/lib/rabbitmq"
    ports:
      - "15672:15672"
  dev-celery-worker:
    extends:
      file: docker-compose.base.yml
      service: dev
    networks:
      dev:
        aliases:
          - celery-worker
    command: "worker"
  dev-dummy-worker:
    extends:
      file: docker-compose.base.yml
      service: dev
    command: "dummy-worker worker --loglevel=debug"
    healthcheck:
      test: "/opt/pycroft/venv/bin/celery -A helpers.dummy_celery_worker inspect ping"
    environment:
      - TEST_HADES_BROKER_URI=amqp://celery:celery@mq:5672/
      - TEST_HADES_RESULT_BACKEND_URI=rpc://celery:celery@mq:5672/
    depends_on:
      - dev-mq
    networks:
      dev:
        aliases:
          - dummy-worker
  dev-mail:
    extends:
      file: docker-compose.base.yml
      service: mail
    networks:
      dev:
        aliases:
          - mail
    ports:
      - "5005:5005"
      - "5006:5006"

volumes:
  home:
  db:
  ldap:
  mq:

networks:
  dev:
