[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.mypy]
plugins = "sqlalchemy.ext.mypy.plugin"
python_version = "3.10"
follow_imports = "silent"
ignore_missing_imports = true
# this list shall slowly grow until it covers the whole codebase.
files = [
    "pycroft/helpers/i18n.py",
]
mypy_path = "stubs"
namespace_packages = true

check_untyped_defs = true
warn_return_any = true
warn_unused_ignores = true
