[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.mypy]
plugins = "sqlalchemy.ext.mypy.plugin"
python_version = "3.10"
follow_imports = "silent"
ignore_missing_imports = true
# this list shall slowly grow until it covers the whole codebase.
files = [
    "pycroft/helpers",
    "pycroft/lib",
    "ldap_sync",
]
mypy_path = "stubs"
namespace_packages = true

# global rules
check_untyped_defs = true
warn_return_any = true
warn_unused_ignores = true
no_strict_optional = true

# stricter rules
[[tool.mypy.overrides]]
module = [
    "ldap_sync",
    "ldap_sync.*",
    "pycroft.lib",
    "pycroft.lib.*",
    "pycroft.helpers",
    "pycroft.helpers.date",
    "pycroft.helpers.errorcode",
    "pycroft.helpers.facilities",
    #"pycroft.helpers.i18n",
    #"pycroft.helpers.interval",
    "pycroft.helpers.net",
    "pycroft.helpers.printing",
    "pycroft.helpers.task",
    "pycroft.helpers.user",
    "pycroft.helpers.utc",
]
disallow_untyped_defs = true
disallow_untyped_calls = true
disallow_untyped_decorators = true
disallow_untyped_globals = true

[tool.pytest]
addopts = "--tb=short --no-header"
markers = [
    "slow: slow test (e.g. testing a timeout)",
    "meta: meta test (e.g. testing validity/consistency of fixtures)",
]
filterwarnings = [
    "always::sqlalchemy.exc.RemovedIn20Warning",
    # fixed in kombu v5.3: https://github.com/celery/kombu/issues/1339
    "ignore::DeprecationWarning:kombu.utils.compat",
    # actually caused by reportlab.
    "ignore:.*load_module.*:DeprecationWarning:importlib._bootstrap",
]
timeout = "10"
