#!/bin/bash

set -euo pipefail

readonly USAGE=("[args]")

readonly DESCRIPTION=(
	"Runs alembic in pycroft model directory.
	Optional arguments are passed to the interpreter."
)

run() {
	cd /opt/pycroft/app
	exec /opt/pycroft/venv/bin/sphinx-autobuild \
	  -v doc doc/_build/html \
	  -jauto \
	  --host 0.0.0.0 \
	  "$@"
}

[[ "$0" == "$BASH_SOURCE" ]] && run "$@" || :
