#!/bin/bash

set -euo pipefail

readonly USAGE=("[args]")

readonly DESCRIPTION=(
	"Run celery worker. Optional arguments are passed to the Celery worker
	executable"
)

run() {
    echo "Started celery worker"
    cd /opt/pycroft/app
	exec -a celery celery -A pycroft.task worker -B "$@"
}

[[ "$0" == "$BASH_SOURCE" ]] && run "$@" || :
