from _typeshed import Incomplete

using_sysrandom: bool

def get_rand_string(length: int = 12, allowed_chars: str = '0123456789abcdef'): ...
def make_msg_id(): ...
def make_id(name): ...
def int_to_decimal_str(integer): ...
def decimal_str_to_int(decimal_string): ...

ADDRESS_MAPPING: Incomplete
