from _typeshed import Incomplete

HHD_VERSION_13: int
HHD_VERSION_14: int
LC_LENGTH_HHD14: int
LC_LENGTH_HHD13: int
LDE_LENGTH_DEFAULT: int
LDE_LENGTH_SPARDA: int
BIT_ENCODING: int
BIT_CONTROLBYTE: int
ENCODING_ASC: int
ENCODING_BCD: int

def parse(code): ...
def clean(code): ...
def bit_sum(num, bits): ...
def digitsum(n): ...
def h(num, l): ...
def asciicode(s): ...
def swap_bytes(s): ...

class FlickerCode:
    version: Incomplete
    lc: Incomplete
    startcode: Incomplete
    de1: Incomplete
    de2: Incomplete
    de3: Incomplete
    rest: Incomplete
    def __init__(self, code, version, lde_len=...) -> None: ...
    def parse(self, code) -> None: ...
    def render(self): ...
    def create_payload(self): ...
    def create_xor_checksum(self, payload): ...
    def create_luhn_checksum(self): ...

class DE:
    length: int
    lde: int
    lde_length: Incomplete
    encoding: Incomplete
    data: Incomplete
    def __init__(self, lde_len) -> None: ...
    version: Incomplete
    def parse(self, data, version): ...
    def set_encoding(self) -> None: ...
    def render_length(self): ...
    def render_data(self): ...

class Startcode(DE):
    control_bytes: Incomplete
    def __init__(self) -> None: ...
    lde: Incomplete
    length: Incomplete
    version: Incomplete
    data: Incomplete
    def parse(self, data): ...
    def render_length(self): ...

def code_to_bitstream(code): ...
def terminal_flicker_unix(
    code,
    field_width: int = 3,
    space_width: int = 3,
    height: int = 1,
    clear: bool = False,
    wait: float = 0.05,
) -> None: ...
