#!/bin/bash

set -euo pipefail

readonly USAGE='[args]'

readonly DESCRIPTION=(
	"Import the legacy database."
)

run() {
	cd /opt/pycroft/app
	/opt/pycroft/venv/bin/python -m legacy.import_legacy "$@"
}

[[ "$0" == "$BASH_SOURCE" ]] && run "$@" || :
