#!/bin/bash

set -euo pipefail

readonly USAGE=("<command> [options]")

readonly DESCRIPTION=(
	"Run the pip of the virtual environment in the project root directory."
)

run() {
	cd /opt/pycroft/app
	/opt/pycroft/venv/bin/pip "$@"
}

[[ "$0" == "$BASH_SOURCE" ]] && run "$@" || :
