#!/bin/bash

set -euo pipefail

readonly USAGE=("[args]")

readonly DESCRIPTION=(
	"Run unit tests. Optional arguments are passed to the unittest module."
)

run() {
	cd /opt/pycroft/app
	exec /opt/pycroft/venv/bin/python -m unittest -v "$@"
}

[[ "$0" == "$BASH_SOURCE" ]] && run "$@" || :
