#!/bin/bash

set -euo pipefail

readonly USAGE=("[args]")

readonly DESCRIPTION=(
	"Run unit tests. Optional arguments are passed to the pytest CLI."
)

run() {
	cd /opt/pycroft/app
	exec pytest -v "$@"
}

[[ "$0" == "$BASH_SOURCE" ]] && run "$@" || :
