#!/bin/bash

set -euo pipefail

readonly USAGE=("[args]")

readonly DESCRIPTION=(
	"Run webpack in project root to build frontend assets (JavaScript, CSS,
	images, fonts). Optional arguments are passed to webpack."
)

run() {
	cd /opt/pycroft/app
	# for debugging purposes
	echo "## npm version:"
	npm --version
	echo "## I am $(id)"
	echo "## webpack is: $(which webpack)"
	echo "## ls -l \$(which webpack):"
	ls -l $(which webpack)
	echo "## node_modules/webpack/bin:"
	file node_modules
	file node_modules/webpack
	file node_modules/webpack/bin
	file node_modules/webpack/bin/webpack.js
	chmod +x ./node_modules/webpack/bin/*
	echo "## npm ll:"
	npm ll

	exec bun run -- webpack --config webpack.config.babel.js "$@"
}

[[ "$0" == "$BASH_SOURCE" ]] && run "$@" || :
