"""Remove config.cache_group_id

Revision ID: 0b69e80a9388
Revises: 28e56bf6f62c
Create Date: 2021-05-20 23:44:18.520232

"""
from alembic import op
import sqlalchemy as sa
import pycroft


# revision identifiers, used by Alembic.
revision = '0b69e80a9388'
down_revision = '28e56bf6f62c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('config_cache_group_id_fkey', 'config', type_='foreignkey')
    op.drop_column('config', 'cache_group_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('config', sa.Column('cache_group_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('config_cache_group_id_fkey', 'config', 'property_group', ['cache_group_id'], ['id'])
    # ### end Alembic commands ###
