"""add account for non-attributable transfers to config

Revision ID: 2d7e4df39a3b
Revises: bc0e0dd480d4
Create Date: 2024-06-06 20:21:16.972195

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b64618e97415"
down_revision = "dda39ad43536"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "config",
        sa.Column(
            "non_attributable_transactions_account_id",
            sa.Integer(),
            nullable=True,
        ),
    )
    op.create_foreign_key(
        None, "config", "account", ["non_attributable_transactions_account_id"], ["id"]
    )
    op.execute(
        "insert into account (name, type, legacy) (select name, type, legacy from (select 'Beiträge, Mitglied nicht zuordenbar' as name, account_type('REVENUE') as type, false as legacy) as a where not exists (select * from account where name = 'Beiträge, Mitglied nicht zuordenbar' and type = 'REVENUE'))"
    )
    op.execute(
        "update config set non_attributable_transactions_account_id=(select id from account where name = 'Beiträge, Mitglied nicht zuordenbar' and type = 'REVENUE')"
    )
    op.alter_column("config", "non_attributable_transactions_account_id", nullable=False)


def downgrade():
    op.drop_constraint(None, "config", type_="foreignkey")
    op.drop_column("config", "non_attributable_transactions_account_id")
    op.create_index(
        "bank_account_activity_imported_at", "bank_account_activity", ["imported_at"], unique=False
    )
