"""allow deleting of unix-accounts

Revision ID: 2a83876e83ae
Revises: f8f1883f81af
Create Date: 2019-10-10 16:10:17.945164

"""
from alembic import op
import sqlalchemy as sa
import pycroft


# revision identifiers, used by Alembic.
revision = '2a83876e83ae'
down_revision = 'f8f1883f81af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_unix_account_id_fkey', 'user', type_='foreignkey')
    op.create_foreign_key('user_unix_account_id_fkey', 'user', 'unix_account', ['unix_account_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_unix_account_id_fkey', 'user', type_='foreignkey')
    op.create_foreign_key('user_unix_account_id_fkey', 'user', 'unix_account', ['unix_account_id'], ['id'])
    # ### end Alembic commands ###
