"""add account for non-attributable transfers to config

Revision ID: 2d7e4df39a3b
Revises: bc0e0dd480d4
Create Date: 2024-06-06 20:21:16.972195

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b64618e97415"
down_revision = "5234d7ac2b4a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "config",
        sa.Column(
            "non_attributable_transactions_account_id",
            sa.Integer(),
            nullable=False,
            server_default="33200",
        ),
    )
    op.create_foreign_key(
        None, "config", "account", ["non_attributable_transactions_account_id"], ["id"]
    )


def downgrade():
    op.drop_constraint(None, "config", type_="foreignkey")
    op.drop_column("config", "non_attributable_transactions_account_id")
    op.create_index(
        "bank_account_activity_imported_at", "bank_account_activity", ["imported_at"], unique=False
    )
