"""remove length restriction on patchport name

Revision ID: 37b57e0baa3a
Revises: cff476c9a54d
Create Date: 2020-02-13 14:27:39.757050

"""
from alembic import op
import sqlalchemy as sa
import pycroft


# revision identifiers, used by Alembic.
revision = '37b57e0baa3a'
down_revision = 'cff476c9a54d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patch_port', 'name',  type_=sa.String())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patch_port', 'name', type_=sa.String(8))
    # ### end Alembic commands ###
