"""allow deleting of switch_ports

Revision ID: 38fa5154b920
Revises: 2a83876e83ae
Create Date: 2019-10-10 16:18:01.348782

"""
from alembic import op
import sqlalchemy as sa
import pycroft


# revision identifiers, used by Alembic.
revision = '38fa5154b920'
down_revision = '2a83876e83ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('patch_port_switch_port_id_fkey', 'patch_port', type_='foreignkey')
    op.create_foreign_key('patch_port_switch_port_id_fkey', 'patch_port', 'switch_port', ['switch_port_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('patch_port_switch_port_id_fkey', 'patch_port', type_='foreignkey')
    op.create_foreign_key('patch_port_switch_port_id_fkey', 'patch_port', 'switch_port', ['switch_port_id'], ['id'])
    # ### end Alembic commands ###
