"""Add password token

Revision ID: 5905825242ff
Revises: d8cfeaaee75d
Create Date: 2021-01-17 11:24:32.036420

"""
from alembic import op
import sqlalchemy as sa
import pycroft


# revision identifiers, used by Alembic.
revision = '5905825242ff'
down_revision = 'd8cfeaaee75d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_reset_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password_reset_token')
    # ### end Alembic commands ###
