"""undo set null for user.unix_account_id

Revision ID: 5b6f5a33e426
Revises: 38fa5154b920
Create Date: 2019-10-13 23:03:12.165450

"""
from alembic import op
import sqlalchemy as sa
import pycroft


# revision identifiers, used by Alembic.
revision = '5b6f5a33e426'
down_revision = '38fa5154b920'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_unix_account_id_fkey', 'user', type_='foreignkey')
    op.create_foreign_key('user_unix_account_id_fkey', 'user', 'unix_account', ['unix_account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_unix_account_id_fkey', 'user', type_='foreignkey')
    op.create_foreign_key('user_unix_account_id_fkey', 'user', 'unix_account', ['unix_account_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
