"""online_reg

Revision ID: 69354f37b510
Revises: c11d3d8b16ae
Create Date: 2020-08-07 17:40:46.517839

"""
from alembic import op
import sqlalchemy as sa
import pycroft


# revision identifiers, used by Alembic.
revision = '69354f37b510'
down_revision = 'c11d3d8b16ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email_forwarded', sa.Boolean(), server_default='True', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email_forwarded')
    # ### end Alembic commands ###
