"""Add permission level for property groups

Revision ID: 7c1927c937af
Revises: ff0dbccdf410
Create Date: 2019-06-01 20:03:20.487616

"""
from alembic import op
import sqlalchemy as sa
import pycroft


# revision identifiers, used by Alembic.
revision = '7c1927c937af'
down_revision = 'ff0dbccdf410'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property_group', sa.Column('permission_level', sa.Integer(), nullable=False, server_default=sa.schema.DefaultClause("0")))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('property_group', 'permission_level')
    # ### end Alembic commands ###
