"""Add confirmed status to transaction

Revision ID: ae8f4b63876a
Revises: ff0dbccdf410
Create Date: 2019-05-31 18:08:19.462983

"""
from alembic import op
import sqlalchemy as sa
import pycroft


# revision identifiers, used by Alembic.
revision = 'ae8f4b63876a'
down_revision = 'ff0dbccdf410'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('confirmed', sa.Boolean(), nullable=False, server_default=sa.schema.DefaultClause("1")))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'confirmed')
    # ### end Alembic commands ###
