"""add field which indicates a building has wifi

Revision ID: cff476c9a54d
Revises: ce8c8cebcbf4
Create Date: 2019-12-18 23:17:55.840237

"""
from alembic import op
import sqlalchemy as sa
import pycroft

# revision identifiers, used by Alembic.
revision = 'cff476c9a54d'
down_revision = 'ce8c8cebcbf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('building',
                  sa.Column('wifi_available', sa.Boolean(), nullable=False, server_default="False"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('building', 'wifi_available')
    # ### end Alembic commands ###
