"""add scheduled tasks

Revision ID: d46e54080f02
Revises: ff0dbccdf410
Create Date: 2019-04-22 11:01:44.659235

"""
from alembic import op
import sqlalchemy as sa
import pycroft


# revision identifiers, used by Alembic.
revision = 'd46e54080f02'
down_revision = 'ff0dbccdf410'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=True),
    sa.Column('type', sa.Enum('USER_MOVE_OUT', 'USER_MOVE_IN', 'USER_MOVE', name='tasktype'), nullable=False),
    sa.Column('due', pycroft.model.types.DateTimeTz(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('created', pycroft.model.types.DateTimeTz(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'EXECUTED', 'FAILED', 'CANCELLED', name='taskstatus'), nullable=False),
    sa.Column('exception_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_log_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['log_entry.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_log_entry_task_id'), 'task_log_entry', ['task_id'], unique=False)
    op.create_table('user_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['task.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    property = sa.table('property', sa.column('name', sa.String))

    op.execute(property.update().where(
        property.c.name == op.inline_literal('user_hosts_change'))
               .values({'name': op.inline_literal('hosts_change')}))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_task')
    op.drop_index(op.f('ix_task_log_entry_task_id'), table_name='task_log_entry')
    op.drop_table('task_log_entry')
    op.drop_table('task')
    # ### end Alembic commands ###

    property = sa.table('property', sa.column('name', sa.String))

    op.execute(property.update().where(
        property.c.name == op.inline_literal('hosts_change'))
               .values({'name': op.inline_literal('user_hosts_change')}))
