"""online_reg

Revision ID: d8cfeaaee75d
Revises: c11d3d8b16ae
Create Date: 2020-08-18 15:04:02.034638

"""
from alembic import op
import sqlalchemy as sa
import pycroft


# revision identifiers, used by Alembic.
revision = 'd8cfeaaee75d'
down_revision = 'c11d3d8b16ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pre_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('registered_at', pycroft.model.types.DateTimeTz(), nullable=False),
    sa.Column('passwd_hash', sa.String(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('email_confirmed', sa.Boolean(), server_default='False', nullable=False),
    sa.Column('email_confirmation_key', sa.String(), nullable=True),
    sa.Column('swdd_person_id', sa.Integer(), nullable=True),
    sa.Column('move_in_date',sa.Date(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_pre_member_room_id'), 'pre_member', ['room_id'], unique=False)

    op.add_column('building', sa.Column('swdd_haus_id', sa.Integer(), nullable=True))

    op.add_column('room', sa.Column('swdd_vo_suchname', sa.String(), nullable=True))
    op.create_unique_constraint('room_swdd_vo_suchname_key', 'room', ['swdd_vo_suchname'])

    op.add_column('user', sa.Column('email_confirmation_key', sa.String(), nullable=True))
    op.add_column('user', sa.Column('email_confirmed', sa.Boolean(), server_default='False', nullable=False))
    op.add_column('user', sa.Column('email_forwarded', sa.Boolean(), server_default='True', nullable=False))
    op.create_unique_constraint('user_swdd_person_id_key', 'user', ['swdd_person_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_swdd_person_id_key', 'user', type_='unique')
    op.drop_column('user', 'email_forwarded')
    op.drop_column('user', 'email_confirmed')
    op.drop_column('user', 'email_confirmation_key')

    op.drop_constraint('room_swdd_vo_suchname_key', 'room', type_='unique')
    op.drop_column('room', 'swdd_vo_suchname')

    op.drop_column('building', 'swdd_haus_id')

    op.drop_index(op.f('ix_pre_member_room_id'), table_name='pre_member')
    op.drop_table('pre_member')
    # ### end Alembic commands ###
