"""add wifi password

Revision ID: f85ef1ef556c
Revises: a522fc7626e9
Create Date: 2019-09-29 10:24:17.113268

"""
from alembic import op
import sqlalchemy as sa
import pycroft


# revision identifiers, used by Alembic.
revision = 'f85ef1ef556c'
down_revision = 'a522fc7626e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('wifi_passwd_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'wifi_passwd_hash')
    # ### end Alembic commands ###
