"""allow deleting of rooms

Revision ID: f8f1883f81af
Revises: ff700db83195
Create Date: 2019-10-10 15:24:33.797124

"""
from alembic import op
import sqlalchemy as sa
import pycroft


# revision identifiers, used by Alembic.
revision = 'f8f1883f81af'
down_revision = 'ff700db83195'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('host_room_id_fkey', 'host', type_='foreignkey')
    op.create_foreign_key('host_room_id_fkey', 'host', 'room', ['room_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('patch_port_room_id_fkey', 'patch_port', type_='foreignkey')
    op.create_foreign_key('patch_port_room_id_fkey', 'patch_port', 'room', ['room_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('room_log_entry_room_id_fkey', 'room_log_entry', type_='foreignkey')
    op.create_foreign_key('room_log_entry_room_id_fkey', 'room_log_entry', 'room', ['room_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('room_log_entry_room_id_fkey', 'room_log_entry', type_='foreignkey')
    op.create_foreign_key('room_log_entry_room_id_fkey', 'room_log_entry', 'room', ['room_id'], ['id'])
    op.drop_constraint('patch_port_room_id_fkey', 'patch_port', type_='foreignkey')
    op.create_foreign_key('patch_port_room_id_fkey', 'patch_port', 'room', ['room_id'], ['id'])
    op.drop_constraint('host_room_id_fkey', 'host', type_='foreignkey')
    op.create_foreign_key('host_room_id_fkey', 'host', 'room', ['room_id'], ['id'])
    # ### end Alembic commands ###
