"""Add Column for interface name

Revision ID: ff0dbccdf410
Revises: 7855ecffe722
Create Date: 2019-04-15 14:48:01.856158

"""
from alembic import op
import sqlalchemy as sa
import pycroft


# revision identifiers, used by Alembic.
revision = 'ff0dbccdf410'
down_revision = '7855ecffe722'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interface', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interface', 'name')
    # ### end Alembic commands ###
