"""Add address relation

Revision ID: ff700db83195
Revises: f85ef1ef556c
Create Date: 2019-10-03 19:15:55.716640

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'ff700db83195'
down_revision = 'f85ef1ef556c'
branch_labels = None
depends_on = None


def upgrade():
    # renaming constraint 'address' → 'building_address'
    op.create_unique_constraint('building_address', 'building', ['street', 'number'])
    op.drop_constraint('address', 'building', type_='unique')

    op.create_table(
        'address',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('street', sa.String(), nullable=False),
        sa.Column('number', sa.String(), nullable=False),
        sa.Column('addition', sa.String(), nullable=True),
        sa.Column('zip_code', sa.String(), nullable=False),
        sa.Column('city', sa.String(), nullable=False, server_default="Dresden"),
        sa.Column('state', sa.String(), nullable=False, server_default="Sachsen"),
        sa.Column('country', sa.String(), nullable=False, server_default="Germany"),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('street', 'number', 'addition', 'zip_code', 'city',
                            'state', 'country')
    )

    op.add_column('config', sa.Column('dummy_address_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'config', 'address', ['dummy_address_id'], ['id'])

    op.add_column('room', sa.Column('address_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_room_address_id'), 'room', ['address_id'], unique=False)
    op.create_foreign_key(None, 'room', 'address', ['address_id'], ['id'])

    op.add_column('user', sa.Column('address_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_user_address_id'), 'user', ['address_id'], unique=False)
    op.create_foreign_key(None, 'user', 'address', ['address_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_index(op.f('ix_user_address_id'), table_name='user')
    op.drop_column('user', 'address_id')
    op.drop_constraint(None, 'room', type_='foreignkey')
    op.drop_index(op.f('ix_room_address_id'), table_name='room')
    op.drop_column('room', 'address_id')
    op.drop_constraint(None, 'config', type_='foreignkey')
    op.drop_column('config', 'dummy_address_id')
    op.drop_index(op.f('ix_patch_port_switch_room_id'), table_name='patch_port')
    op.drop_index(op.f('ix_patch_port_room_id'), table_name='patch_port')
    op.drop_table('address')
    op.create_unique_constraint('address', 'building', ['street', 'number'])
    op.drop_constraint('building_address', 'building', type_='unique')
    # ### end Alembic commands ###
