#!/bin/bash

set -euo pipefail
LOCKDIR=/opt/pycroft/venv

. /container/common/locking.sh

function execute_hook() {
  set -x
  PIP="/opt/pycroft/venv/bin/uv pip"
  UV="/opt/pycroft/venv/bin/uv"
  PY="/opt/pycroft/venv/bin/python"

  if [[ ! -f /opt/pycroft/venv/bin/activate ]]; then
    echo "Creating virtual environment"
    python3 -m venv /opt/pycroft/venv
  fi

  if $PY -c 'import importlib.util as u; exit(0 if u.find_spec("pycroft") is not None else 1)'; then
    echo "Pip packages present, nothing to do"
    return
  fi

  $PY -m ensurepip
  $PY -m pip install uv
  $PIP install wheel

  echo "No pip packages found, installing requirements"
  cd /opt/pycroft/app
  $PIP install --upgrade uv
  ls `$UV cache dir`
  $PIP sync requirements.dev.txt
  $PIP install -e '.[dev]' 'wtforms-widgets @ ./deps/wtforms-widgets'
}

[[ -d $LOCKDIR ]] || mkdir $LOCKDIR
execute_with_dirlock $LOCKDIR execute_hook
