#!/bin/bash

set -euo pipefail
LOCKDIR=/opt/pycroft/app/node_modules

. /container/common/locking.sh

function execute_hook() {
  set -x
  cd /opt/pycroft/app

  if shopt -s nullglob dotglob; files=(node_modules/*); (( ${#files[@]} > 0 )); then
    return
  fi

  bun install --frozen-lockfile
}

[[ -d $LOCKDIR ]] || mkdir $LOCKDIR
execute_with_dirlock $LOCKDIR execute_hook
