#!/bin/bash

set -euo pipefail

# Fix Celery on Python 3.9
# Adapted from https://github.com/ddliu/dockerfiles/blob/master/special/nc/ns/fix.sh
# https://github.com/celery/celery/issues/4500
TARGET=/opt/pycroft/venv/lib/python3.9/site-packages/

# if `kombu/async` does not exist anymore, this has been patched already
UNPATCHED_INDICATOR_DIR="${TARGET}kombu/async"
if [[ ! -e $UNPATCHED_INDICATOR_DIR ]]
then
    echo "Skipping celery async patch as '${UNPATCHED_INDICATOR_DIR}' does not exist."
    exit
fi

echo "Patching celery to ensure Python 3.9 compatibility"
find "$TARGET" -type f -iname "*.py" -exec sed -i 's/kombu\.async\b/kombu.asynchronous/g' {} +

cd "$TARGET"/kombu
echo "Patching kombu to ensure Python 3.9 compatibility..."
    mv async asynchronous
    find . -type f -iname "*.py" -exec sed -i 's/\basync\b/asynchronous/g' {} +
echo "...done"
