from _typeshed import Incomplete

def add_currency_pre_processor(currency, overwrite: bool = ...): ...
def date_fixup_pre_processor(transactions, tag, tag_dict, *args): ...
def date_cleanup_post_processor(transactions, tag, tag_dict, result): ...
def mBank_set_transaction_code(transactions, tag, tag_dict, *args): ...

iph_id_re: Incomplete

def mBank_set_iph_id(transactions, tag, tag_dict, *args): ...

tnr_re: Incomplete

def mBank_set_tnr(transactions, tag, tag_dict, *args): ...

DETAIL_KEYS: Incomplete
GVC_KEYS: Incomplete

def transaction_details_post_processor(transactions, tag, tag_dict, result): ...
