name: Pycroft CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: pre-commit/action@v2.0.3
  python-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out pycroft and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: ensure presence of `wheel`
        run: pip install wheel
      - name: install pip dependencies
        run: pip install -r requirements.txt -r requirements.dev.txt
      - name: Execute mypy
        run: |
          mypy | tee mypy_results.log
          python ./scripts/render_mypy_results.py mypy_results.log
  npm-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: npm ci
    - run: npm run build
    - name: Check for outdated NPM packages
      run: |
        (npm outdated --json | tee outdated.json) || [[ $? == 1 ]]
        python ./scripts/render_outdated.py outdated.json >> "${GITHUB_STEP_SUMMARY}"
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
           submodules: 'true'
      - name: Fix permissions
        run: sudo chmod -R a+rw .
      - name: Build the Docker image
        run: docker-compose -f docker-compose.prod.yml build
      - name: Login to GitLab Registry
        uses: docker/login-action@v1
        with:
          registry: registry.agdsn.de
          username: "github-actions"
          password: ${{ secrets.GITLAB_REGISTRY_PASSWORD }}
      - name: Tag built image
        run: docker tag agdsn/pycroft-prod:latest registry.agdsn.de/agdsn/coreos/pycroft/pycroft:${GITHUB_REF##*/}
      - name: Push to GitLab registry
        run: docker push registry.agdsn.de/agdsn/coreos/pycroft/pycroft:${GITHUB_REF##*/}
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
           submodules: 'true'
      - name: Fix permissions
        run: sudo chmod -R a+rw .
      - name: Build
        run: docker-compose -f docker-compose.test.yml build
      - name: Run test-app entrypoints
        run: docker-compose -f docker-compose.test.yml run --rm test-app /bin/true
      - name: Start
        run: docker-compose -f docker-compose.test.yml up -d
      - name: Run webpack
        run: docker-compose -f docker-compose.test.yml run --rm test-app webpack --mode production
      - name: Run tests
        run: docker-compose -f docker-compose.test.yml run --rm test-app test

