MAX_CONTENT_LENGTH = 67108864
UPLOAD_FOLDER = '/tmp'
SECRET_KEY = 'eiNohfaefaig5Iek6oshai0eijuph4ohla6Eo1vi5bahnaeh3Bah7ohy1einuaxu'
BABEL_DEFAULT_LOCALE = 'de'
BABEL_DEFAULT_TIMEZONE = 'Europe/Berlin'
